"""increased html size to max

Revision ID: 6558ab9c45fe
Revises: b297de4c9bf9
Create Date: 2019-07-23 11:42:11.961282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6558ab9c45fe'
down_revision = 'b297de4c9bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', 'html',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10485760),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', 'html',
               existing_type=sa.String(length=10485760),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
